---
title: "pinguim_markdown"
output: html_document
date: "2023-06-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggrepel)
library(patchwork)
library(socviz)
library(gapminder)

pg_lter = read.csv("C:/Users/danie/OneDrive/Área de Trabalho/A2_asla/penguins_lter.csv")
pg_size = read.csv("C:/Users/danie/OneDrive/Área de Trabalho/A2_asla/penguins_size.csv")

paleta_penguins = c("#FF8204", "#C55BCA", "#0E7076")
paleta_penguins_dois = c("adelie", "chinstrap", "gentoo")
```

```{r}
sample_n(pg_lter, 10)
```
```{r}
sample_n(pg_size, 10)
```
## Observando os dados e testando gráficos
```{r}
pg_size %>% group_by(island, species) %>% summarize(contagem = n()) %>% 
  ggplot(aes(x = island, y = species)) +
  geom_col()
```


```{r}
pg_size %>% group_by(species, island) %>% summarize(contagem = n()) %>% 
  mutate(frequencia  = contagem / sum(contagem)) %>% 
  ggplot(aes(x = species)) +
  geom_bar()

pg_size %>% 
  ggplot(aes(x = species)) +
  geom_bar(mapping = aes(y = ..prop.., group = 1))
```
Análise exploratória das ilhas

```{r}
# pg_size %>% group_by(island) %>% 
#   ggplot(aes(x = spe, y = species)) +
#   geom_point()

# proporão de espécie por ilha
# quantidade total dos pinguins?
ggplot(pg_size, aes(x = species)) +
  geom_bar()

ggplot(pg_size, aes(x = species)) +
  geom_bar(aes(y = ..prop..))

ggplot(pg_size, aes(x = species)) +
  geom_bar(aes(group = island, y = ..prop..))

pg_size %>% group_by(island) %>% 
  summarize(contagem = n()) %>% 
  mutate(porcentagem = contagem / sum(contagem)) %>% 
  ggplot(aes(x = island, y = porcentagem)) +
  geom_col() +
  scale_y_continuous(labels = scales::percent) +
  labs(title = "Distribuição dos pinguins por ilha",
       x = "Ilha")

pg_size %>% group_by(island, species) %>% 
  summarize(contagem = n()) %>% 
  mutate(porcentagem = contagem / sum(contagem)) %>% 
  ggplot(aes(x = island, y = porcentagem)) +
  geom_col() +
  scale_y_continuous(labels = scales::percent) +
  facet_wrap(~species) +
  labs(title = "Distribuição dos pinguins por ilha",
       x = "Ilha")

pg_size %>% group_by(island, species) %>% 
  summarize(contagem = n()) %>% 
  mutate(porcentagem = contagem / sum(contagem))

# esse fico bao
pg_size %>% group_by(island, species) %>%
  summarize(contagem = n()) %>%
  mutate(porcentagem = contagem / sum(contagem)) %>%
  ggplot(aes(x = island, y = porcentagem, fill = species)) +
  geom_col() +
  scale_y_continuous(labels = scales::percent) +
  labs(title = "Distribuição dos pinguins por ilha",
       x = "Ilha") +
  scale_fill_manual(values = paleta_penguins)
```
```{r}
pg_size %>% group_by(island) %>% 
  summarize(contagem = n()) %>% 
  mutate(porcentagem = contagem / sum(contagem)) %>% 
  ggplot(aes(x = island, y = contagem)) +
  geom_col()

pg_size %>% group_by(species) %>% 
  summarize(contagem = n()) %>% 
  mutate(porcentagem = contagem / sum(contagem)) %>% 
  ggplot(aes(x = species, y = porcentagem, fill = species)) +
  geom_col() +
  scale_fill_manual(values = paleta_penguins) +
  scale_y_continuous(labels = scales::percent) +
  labs(title = "Porcentagem de pinguins por espécie")

pg_size %>% group_by(island, species) %>% 
  summarize(contagem = n()) %>% 
  mutate(porcentagem = contagem / sum(contagem)) %>% 
  ggplot(aes(x = island, y = contagem)) +
  geom_col()
```

```{r pie chart}
trem_species <- pg_size %>% group_by(species) %>% 
  summarize(contagem = n()) %>% 
  mutate(porcentagem = contagem / sum(contagem))

trem_ilhas <- pg_size %>% group_by(island) %>% 
  summarize(contagem = n()) %>% 
  mutate(porcentagem = contagem / sum(contagem))

df_island_species <- pg_size %>% group_by(island, species) %>%
  summarize(contagem = n()) %>%
  mutate(porcentagem = contagem / sum(contagem))

ilhas <- c(trem_ilhas$island[1], trem_ilhas$island[2], trem_ilhas$island[3])
populacao_ilhas <- c(trem_ilhas$porcentagem[1], trem_ilhas$porcentagem[2], trem_ilhas$porcentagem[3])
ilhas
populacao_ilhas


# porcentagem de cada espécie por ilha
plot3 <- 
pg_size %>% group_by(island, species) %>%
  summarize(contagem = n()) %>%
  mutate(porcentagem = contagem / sum(contagem)) %>%
  ggplot(aes(x = island, y = porcentagem, fill = species)) +
  geom_col() +
  scale_y_continuous(labels = scales::percent) +
  labs(title = "Porcentagem de espécies por ilha",
       x = "Ilha",
       y = "Porcentagem") +
  scale_fill_manual(values = paleta_penguins)
plot3

df_island_species

df_island_species[df_island_species$island == "Biscoe",]
df_island_species[df_island_species$island == "Dream",]
df_island_species[df_island_species$island == "Torgersen",]

pie(df_island_species[df_island_species$island == "Biscoe",]$porcentagem, df_island_species[df_island_species$island == "Biscoe",]$species, radius = populacao_ilhas[ilhas %in% "Biscoe"], col = c("#FF8204", "#0E7076"))
pie(df_island_species[df_island_species$island == "Dream",]$porcentagem, df_island_species[df_island_species$island == "Dream",]$species, radius = populacao_ilhas[ilhas %in% "Dream"], col = paleta_penguins)
pie(df_island_species[df_island_species$island == "Torgersen",]$porcentagem, df_island_species[df_island_species$island == "Torgersen",]$species, radius = populacao_ilhas[ilhas %in% "Torgersen"], col = paleta_penguins)
```



```{r gráficos "finais"}
plot1 <- 
pg_size %>% group_by(species) %>% 
  summarize(contagem = n()) %>% 
  mutate(porcentagem = contagem / sum(contagem)) %>% 
  ggplot(aes(x = species, y = porcentagem, fill = species)) +
  geom_col() +
  scale_fill_manual(values = paleta_penguins) +
  scale_y_continuous(labels = scales::percent) +
  labs(title = "Porcentagem de pinguins por espécie",
       x = "Espécie",
       y = "Porcentagem")

plot11 <- 
pg_size %>% group_by(species) %>% 
  summarize(contagem = n()) %>% 
  mutate(porcentagem = contagem / sum(contagem)) %>% 
  ggplot(aes(x = species, y = contagem, fill = species)) +
  geom_col() +
  scale_fill_manual(values = paleta_penguins) +
  labs(title = "Porcentagem de pinguins por espécie",
       x = "Espécie",
       y = "Contagem")

plot11

# porcetagem  dos pinguins por ilha
plot2 <- 
pg_size %>% group_by(island) %>% 
  summarize(contagem = n()) %>% 
  mutate(porcentagem = contagem / sum(contagem)) %>% 
  ggplot(aes(x = island, y = porcentagem)) +
  geom_col() +
  scale_y_continuous(labels = scales::percent) +
  labs(title = "Distribuição dos pinguins por ilha",
       x = "Ilha",
       y = "Porcentagem")
plot21 <- 
pg_size %>% group_by(island) %>% 
  summarize(contagem = n()) %>% 
  mutate(porcentagem = contagem / sum(contagem)) %>% 
  ggplot(aes(x = island, y = contagem)) +
  geom_col() +
  labs(title = "Distribuição dos pinguins por ilha",
       x = "Ilha",
       y = "Contagem")
plot22 <- 
pg_size %>% group_by(island, species) %>% 
  summarize(contagem = n()) %>% 
  mutate(porcentagem = contagem / sum(contagem)) %>% 
  ggplot(aes(x = species, y = contagem, fill = species)) +
  geom_col() +
  scale_fill_manual(values = paleta_penguins) +
  facet_wrap(~island) +
  labs(title = "Distribuição dos pinguins por espécie por ilha",
       x = "Espécie",
       y = "Quantidade")
plot22

# porcentagem de cada espécie por ilha
plot3 <- 
pg_size %>% group_by(island, species) %>%
  summarize(contagem = n()) %>%
  mutate(porcentagem = contagem / sum(contagem)) %>%
  ggplot(aes(x = island, y = porcentagem, fill = species)) +
  geom_col() +
  scale_y_continuous(labels = scales::percent) +
  labs(title = "Porcentagem de espécies por ilha",
       x = "Ilha",
       y = "Porcentagem") +
  scale_fill_manual(values = paleta_penguins)
plot3
```
## Gráficos finais
```{r gráficos "finais"}
# porcetagem em relação ao total de cada espécie de pinguim
# com texto junto da barra
plot1_novo <- plot1 + 
  geom_text(aes(label = contagem) , size = 10, hjust = 1, vjust = 0.5) +
  coord_flip()
# sem texto junto da barra
plot11_novo <- plot1 +
  coord_flip()

# Distribuição do número de pinguins por ilha
# com texto junto da barra
plot2_novo <- plot2 + coord_flip() +
  geom_text(aes(label = contagem) , size = 10, hjust = 1, vjust = 0.5) +
  coord_flip()
# sem texto junto da barra
plot21_novo <- plot2 +
  coord_flip()

# porcetagem de espécies por ilha
plot3_novo <- plot3 + coord_flip()

plot1_novo
plot2_novo
plot3_novo

plot11_novo/
plot21_novo/
plot3_novo

# distribuição de pinguim por ilha e por espécie
plot22

# porcetagem de pinguins por ilha em pizza
# com raio da pizza sendo a quantidade de pinguins na ilha em proporção
df_island_species <- pg_size %>% group_by(island, species) %>%
  summarize(contagem = n()) %>%
  mutate(porcentagem = contagem / sum(contagem))
pie(df_island_species[df_island_species$island == "Biscoe",]$porcentagem, df_island_species[df_island_species$island == "Biscoe",]$species, radius = populacao_ilhas[ilhas %in% "Biscoe"], col = c("#FF8204", "#0E7076"))
pie(df_island_species[df_island_species$island == "Dream",]$porcentagem, df_island_species[df_island_species$island == "Dream",]$species, radius = populacao_ilhas[ilhas %in% "Dream"], col = paleta_penguins)
pie(df_island_species[df_island_species$island == "Torgersen",]$porcentagem, df_island_species[df_island_species$island == "Torgersen",]$species, radius = populacao_ilhas[ilhas %in% "Torgersen"], col = paleta_penguins)
```